/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module my_module(in, clk, out);
  input clk;
  input in;
  wire n1;
  wire n2;
  wire n3;
  wire n4;
  wire n5;
  wire n6;
  output out;
  sky130_fd_sc_hd__dfxtp_4 f1 (
    .CLK(clk),
    .D(in),
    .Q(n1)
  );
  sky130_fd_sc_hd__dfxtp_4 f2 (
    .CLK(clk),
    .D(n6),
    .Q(out)
  );
  sky130_fd_sc_hd__inv_1 u3 (
    .A(n1),
    .Y(n2)
  );
  sky130_fd_sc_hd__inv_1 u4 (
    .A(n2),
    .Y(n3)
  );
  sky130_fd_sc_hd__nand2_2 u5 (
    .A(n3),
    .B(n2),
    .Y(n5)
  );
  sky130_fd_sc_hd__nand2_1 u6 (
    .A(n1),
    .B(n3),
    .Y(n4)
  );
  sky130_fd_sc_hd__nor2_1 u7 (
    .A(n4),
    .B(n5),
    .Y(n6)
  );
endmodule
